insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Arch Trayes', 'Crest Line', '1993-02-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kirsten Phaup', 'Michigan', '2019-01-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Elli Yabsley', 'West', '1983-11-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Vivyanne Scholey', 'Caliangt', '1985-12-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Shandy Torritti', 'Hanson', '2012-04-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Virgie Cordeau', 'Hoard', '2019-12-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Johnnie Dowderswell', 'Drewry', '1988-10-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kylen Drable', 'Commercial', '1996-08-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cullin O''Nowlan', 'Bluejay', '1984-11-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Catlee Filimore', 'Annamark', '2006-03-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Benjie Fenna', 'Gerald', '1994-12-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Christel Louth', 'Dawn', '1979-05-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Emlynn Chieze', 'Straubel', '2015-05-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Marrissa Houldey', '5th', '2012-11-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Goldarina Feander', 'Corry', '1973-11-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Shannen Greason', 'Pleasure', '1998-01-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Britni Lannon', 'Service', '1999-10-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jimmy Wloch', 'Kenwood', '2011-10-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Mariska Bushby', 'Packers', '1980-01-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Blinny Jozefowicz', 'Beilfuss', '1977-05-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Quinn Dickons', 'Lillian', '1984-08-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Matelda Tame', 'Darwin', '2005-09-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sergent Wynne', 'Spenser', '1990-07-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gabie Gunn', 'Thompson', '2015-12-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Banky McArtan', 'Continental', '2015-06-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Meta Mannakee', 'Vernon', '1989-07-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bettye Reisen', 'Jenna', '2000-03-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Retha Stone Fewings', 'Pawling', '1988-12-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Maurise Morrall', 'Farmco', '2012-05-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kalvin Andric', 'Hoepker', '1978-06-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Joshua Attenbrow', 'Havey', '2019-01-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gerry McMillan', 'Hintze', '1973-04-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Liam Gajewski', 'Laurel', '1979-11-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lothaire Cranstone', 'Dayton', '1984-09-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Haroun Penke', 'Mifflin', '1989-06-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Masha Toupe', 'Sachs', '1975-08-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kevin Harborow', 'Onsgard', '1974-05-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Krissie Karsh', 'Stone Corner', '2008-09-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Alfred Debling', 'Trailsway', '1978-10-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bartie Durnan', 'Darwin', '2005-03-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Beckie Daughtery', 'Kropf', '1982-11-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Corney Brecher', 'Warner', '1993-01-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Daren Bentinck', 'Sunbrook', '2006-03-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Priscella Searle', 'Rigney', '1994-04-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Doralia Skala', '3rd', '2011-02-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Marius Andree', 'Loomis', '2003-11-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Vasilis Brum', 'Buell', '2004-05-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Silvanus Shutle', 'Sommers', '2019-02-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Trudi Kilius', 'Kingsford', '1980-11-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Henri Glendza', 'Mifflin', '1975-05-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rube Renac', 'Brickson Park', '1977-06-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dav Hanselmann', 'Kim', '1975-01-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rock Marriot', 'South', '1970-06-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cathrine Begley', 'Elmside', '2017-04-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Wini L''argent', 'Clarendon', '1983-06-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Douglas Aldus', 'Oak Valley', '1971-04-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bayard Biagioni', 'Loomis', '2011-07-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Hershel Woolager', 'Reindahl', '2015-03-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Chere Rhys', 'Fairfield', '1979-04-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kally Manclark', 'Lotheville', '2014-12-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Del Grouvel', 'Utah', '1995-02-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Aleen Pawle', 'La Follette', '2000-04-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Diena Stook', 'Village Green', '1984-08-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cristie Furminger', 'Rockefeller', '2014-06-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ruthie Baswall', 'Birchwood', '1994-06-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Caralie Bickle', 'Namekagon', '2001-08-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Greg Konzel', 'Talmadge', '1990-09-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Celestyn Colley', 'Walton', '1996-08-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Annabela Reynault', 'International', '1980-11-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Liane Beechcraft', 'Pearson', '2001-01-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Shoshanna Sancroft', 'Goodland', '2012-06-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Marlow Proffitt', 'Thackeray', '2001-02-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Raynor Kersley', 'Moland', '1996-06-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Constantin Spadaro', 'Dexter', '1983-08-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Norina Brodeur', 'Reindahl', '1987-05-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Winne Osbourn', 'Messerschmidt', '2004-05-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Prue Hallaways', 'Summer Ridge', '1978-03-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nicolette Challenor', 'Swallow', '1973-10-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jed Dawbery', 'Walton', '1983-12-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gertrudis Shatford', '7th', '2007-01-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ange Paver', 'Eastwood', '1993-03-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('El Marder', 'Derek', '2014-12-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Perren MacGorman', 'Iowa', '1998-10-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Doreen Notman', 'Corben', '1987-11-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Michel Sparham', 'Forster', '1986-08-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rolland Maro', 'Lukken', '2003-02-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Torrence Gulliman', 'Clemons', '1973-01-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Malachi Bower', 'Dwight', '2003-12-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Clea Magenny', 'Eagan', '1988-12-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Merle Milligan', 'Southridge', '1988-06-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Shari Emberson', 'Oak', '1975-08-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Franny Drysdale', 'Park Meadow', '2004-09-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Herschel Delafoy', 'Sloan', '1980-04-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Mame Grangier', 'Northview', '2000-08-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Filbert Jallin', 'Magdeline', '1991-10-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Reuven Lawlings', 'Basil', '1998-06-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jason Pietzner', 'Warrior', '1974-06-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Delora Brymham', 'Scoville', '1984-05-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Matelda Simonot', 'Kennedy', '1998-06-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Carleton Di Franceshci', 'High Crossing', '2005-04-21');
