insert into tren (modelo, capacidad) values ('7 Series', 1);
insert into tren (modelo, capacidad) values ('Rodeo', 2);
insert into tren (modelo, capacidad) values ('Lumina', 3);
insert into tren (modelo, capacidad) values ('3500', 4);
insert into tren (modelo, capacidad) values ('Club Wagon', 5);
insert into tren (modelo, capacidad) values ('Frontier', 6);
insert into tren (modelo, capacidad) values ('F430', 7);
insert into tren (modelo, capacidad) values ('900', 8);
insert into tren (modelo, capacidad) values ('E-Series', 9);
insert into tren (modelo, capacidad) values ('SLK-Class', 10);
insert into tren (modelo, capacidad) values ('SLS AMG', 11);
insert into tren (modelo, capacidad) values ('Aerio', 12);
insert into tren (modelo, capacidad) values ('Baja', 13);
insert into tren (modelo, capacidad) values ('Silverado 1500', 14);
insert into tren (modelo, capacidad) values ('GS', 15);
insert into tren (modelo, capacidad) values ('5 Series', 16);
insert into tren (modelo, capacidad) values ('Cavalier', 17);
insert into tren (modelo, capacidad) values ('C70', 18);
insert into tren (modelo, capacidad) values ('TT', 19);
insert into tren (modelo, capacidad) values ('Reliant', 20);
insert into tren (modelo, capacidad) values ('Ipsum', 21);
insert into tren (modelo, capacidad) values ('Corsica', 22);
insert into tren (modelo, capacidad) values ('Murciélago', 23);
insert into tren (modelo, capacidad) values ('M3', 24);
insert into tren (modelo, capacidad) values ('9000', 25);
insert into tren (modelo, capacidad) values ('Colt Vista', 26);
insert into tren (modelo, capacidad) values ('SX4', 27);
insert into tren (modelo, capacidad) values ('Contour', 28);
insert into tren (modelo, capacidad) values ('S10', 29);
insert into tren (modelo, capacidad) values ('S8', 30);
insert into tren (modelo, capacidad) values ('Alcyone SVX', 31);
insert into tren (modelo, capacidad) values ('Elise', 32);
insert into tren (modelo, capacidad) values ('Corvette', 33);
insert into tren (modelo, capacidad) values ('1500 Club Coupe', 34);
insert into tren (modelo, capacidad) values ('XT', 35);
insert into tren (modelo, capacidad) values ('RDX', 36);
insert into tren (modelo, capacidad) values ('80', 37);
insert into tren (modelo, capacidad) values ('T100 Xtra', 38);
insert into tren (modelo, capacidad) values ('Solstice', 39);
insert into tren (modelo, capacidad) values ('911', 40);
insert into tren (modelo, capacidad) values ('Fox', 41);
insert into tren (modelo, capacidad) values ('1500 Club Coupe', 42);
insert into tren (modelo, capacidad) values ('Sequoia', 43);
insert into tren (modelo, capacidad) values ('Savana 1500', 44);
insert into tren (modelo, capacidad) values ('Navigator L', 45);
insert into tren (modelo, capacidad) values ('Prius', 46);
insert into tren (modelo, capacidad) values ('Express 3500', 47);
insert into tren (modelo, capacidad) values ('Sonoma', 48);
insert into tren (modelo, capacidad) values ('207', 49);
insert into tren (modelo, capacidad) values ('Cooper Clubman', 50);
insert into tren (modelo, capacidad) values ('Corsica', 51);
insert into tren (modelo, capacidad) values ('Celica', 52);
insert into tren (modelo, capacidad) values ('Venture', 53);
insert into tren (modelo, capacidad) values ('Boxster', 54);
insert into tren (modelo, capacidad) values ('Miata MX-5', 55);
insert into tren (modelo, capacidad) values ('IS-F', 56);
insert into tren (modelo, capacidad) values ('Caprice Classic', 57);
insert into tren (modelo, capacidad) values ('FF', 58);
insert into tren (modelo, capacidad) values ('Escalade ESV', 59);
insert into tren (modelo, capacidad) values ('9000', 60);
insert into tren (modelo, capacidad) values ('MX-5', 61);
insert into tren (modelo, capacidad) values ('Ram 1500', 62);
insert into tren (modelo, capacidad) values ('ES', 63);
insert into tren (modelo, capacidad) values ('Passat', 64);
insert into tren (modelo, capacidad) values ('Ram 3500', 65);
insert into tren (modelo, capacidad) values ('Tracer', 66);
insert into tren (modelo, capacidad) values ('Mountaineer', 67);
insert into tren (modelo, capacidad) values ('H1', 68);
insert into tren (modelo, capacidad) values ('Cabriolet', 69);
insert into tren (modelo, capacidad) values ('GX', 70);
insert into tren (modelo, capacidad) values ('Spyder', 71);
insert into tren (modelo, capacidad) values ('Maxima', 72);
insert into tren (modelo, capacidad) values ('350Z', 73);
insert into tren (modelo, capacidad) values ('Eurovan', 74);
insert into tren (modelo, capacidad) values ('Excursion', 75);
insert into tren (modelo, capacidad) values ('Town & Country', 76);
insert into tren (modelo, capacidad) values ('Discovery', 77);
insert into tren (modelo, capacidad) values ('FJ Cruiser', 78);
insert into tren (modelo, capacidad) values ('G-Series G30', 79);
insert into tren (modelo, capacidad) values ('Range Rover', 80);
insert into tren (modelo, capacidad) values ('Dakota Club', 81);
insert into tren (modelo, capacidad) values ('Mustang', 82);
insert into tren (modelo, capacidad) values ('3500', 83);
insert into tren (modelo, capacidad) values ('Ranger', 84);
insert into tren (modelo, capacidad) values ('Durango', 85);
insert into tren (modelo, capacidad) values ('Savana 3500', 86);
insert into tren (modelo, capacidad) values ('V50', 87);
insert into tren (modelo, capacidad) values ('100', 88);
insert into tren (modelo, capacidad) values ('B-Series', 89);
insert into tren (modelo, capacidad) values ('Mustang', 90);
insert into tren (modelo, capacidad) values ('Town & Country', 91);
insert into tren (modelo, capacidad) values ('9-4X', 92);
insert into tren (modelo, capacidad) values ('Pilot', 93);
insert into tren (modelo, capacidad) values ('SLK-Class', 94);
insert into tren (modelo, capacidad) values ('Eclipse', 95);
insert into tren (modelo, capacidad) values ('RAV4', 96);
insert into tren (modelo, capacidad) values ('IS', 97);
insert into tren (modelo, capacidad) values ('3 Series', 98);
insert into tren (modelo, capacidad) values ('9000', 99);
insert into tren (modelo, capacidad) values ('MX-5', 100);
